allowBuilds:
  '@journeyapps/wa-sqlite': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  lefthook: true
  msw: false
  sharp: false
  yarn: false

minimumReleaseAge: 0

overrides:
  zod: $zod

packageExtensions:
  '@neondatabase/auth':
    peerDependencies:
      lucide-react: '*'
