import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { is } from "drizzle-orm";
import { getTableConfig, PgTable } from "drizzle-orm/pg-core";
// biome-ignore lint/performance/noNamespaceImport: generator introspects every exported table from the Drizzle barrel; a named list would defeat the "new tables sync by default" goal
import * as schema from "../src/db/schema";

// Server-only: excluded from sync. Opt-out denylist — new tables sync by default
// and will surface in codegen output immediately after they are added to the
// Drizzle schema. Add a table here only if it must never sync to the client.
export const SERVER_ONLY_TABLES: ReadonlySet<string> = new Set([
  "users",
  "user_preferences",
  "push_subscriptions",
]);

const GENERATED_HEADER_TS = `// Generated by scripts/generate-sync.ts -- do not edit by hand.
// Run \`pnpm sync:generate\` to regenerate.`;

const GENERATED_HEADER_YAML = `# Generated by scripts/generate-sync.ts -- do not edit by hand.
# Run \`pnpm sync:generate\` to regenerate.`;

const COMMENT_BOOLEAN = [
  "// PostgreSQL booleans are stored as integers (0/1) in SQLite.",
  "// Client code must convert to/from boolean.",
];
const COMMENT_ARRAY = [
  "// PostgreSQL text[] arrays are serialized as JSON strings by PowerSync.",
  "// Client code must JSON.parse() this value to get the array.",
];
const COMMENT_NUMERIC = [
  "// Stored as text to preserve exact decimal precision (server uses numeric(10,2)).",
  "// Client code must parse this value as a number when displaying.",
];

type NeedsComment = "boolean" | "array" | "numeric" | null;

export type SyncedColumnInfo = {
  name: string;
  psType: "text" | "integer";
  needsComment: NeedsComment;
};

export type SyncedTableInfo = {
  name: string;
  columns: readonly SyncedColumnInfo[];
  columnNames: readonly string[];
};

export function mapColumnType(columnType: string): {
  psType: "text" | "integer";
  needsComment: NeedsComment;
} {
  switch (columnType) {
    case "PgUUID":
    case "PgText":
    case "PgVarchar":
    case "PgChar":
    case "PgTimestamp":
    case "PgTimestampString":
    case "PgDate":
    case "PgDateString":
    case "PgTime":
      return { psType: "text", needsComment: null };
    case "PgArray":
      return { psType: "text", needsComment: "array" };
    case "PgNumeric":
      return { psType: "text", needsComment: "numeric" };
    case "PgInteger":
    case "PgSmallInt":
    case "PgSerial":
    case "PgSmallSerial":
    case "PgBigSerial53":
    case "PgBigSerial64":
      return { psType: "integer", needsComment: null };
    case "PgBoolean":
      return { psType: "integer", needsComment: "boolean" };
    default:
      throw new Error(
        `Unsupported Drizzle columnType "${columnType}". Add a mapping in scripts/generate-sync.ts.`
      );
  }
}

export function collectSyncedTables(
  schemaExports: Record<string, unknown>,
  denylist: ReadonlySet<string>
): readonly SyncedTableInfo[] {
  const tables: SyncedTableInfo[] = [];

  for (const value of Object.values(schemaExports)) {
    if (!is(value, PgTable)) {
      continue;
    }
    const cfg = getTableConfig(value);
    if (denylist.has(cfg.name)) {
      continue;
    }

    const columnNames: string[] = [];
    const columns: SyncedColumnInfo[] = [];

    for (const col of cfg.columns) {
      columnNames.push(col.name);
      if (col.name === "id") {
        continue;
      }
      let mapped: ReturnType<typeof mapColumnType>;
      try {
        mapped = mapColumnType(col.columnType);
      } catch (err) {
        const detail = err instanceof Error ? err.message : String(err);
        throw new Error(`${cfg.name}.${col.name}: ${detail}`, { cause: err });
      }
      columns.push({
        name: col.name,
        psType: mapped.psType,
        needsComment: mapped.needsComment,
      });
    }

    tables.push({ name: cfg.name, columns, columnNames });
  }

  // Byte-order comparison (no locale dependency) — keeps generator output
  // identical across macOS, Linux, and CI regardless of ICU collation rules
  // for underscores vs. letters.
  return tables.sort((a, b) => {
    if (a.name < b.name) {
      return -1;
    }
    if (a.name > b.name) {
      return 1;
    }
    return 0;
  });
}

export function generateSyncConfigYaml(
  tables: readonly SyncedTableInfo[]
): string {
  const lines = [
    GENERATED_HEADER_YAML,
    "",
    "config:",
    "  edition: 3",
    "",
    "streams:",
    "  user_data:",
    "    auto_subscribe: true",
    "    queries:",
  ];
  for (const t of tables) {
    lines.push(
      `      - SELECT * FROM ${t.name} WHERE user_id = auth.user_id()`
    );
  }
  return `${lines.join("\n")}\n`;
}

function commentLinesFor(needsComment: NeedsComment): readonly string[] {
  if (needsComment === "array") {
    return COMMENT_ARRAY;
  }
  if (needsComment === "boolean") {
    return COMMENT_BOOLEAN;
  }
  if (needsComment === "numeric") {
    return COMMENT_NUMERIC;
  }
  return [];
}

export function generateClientSchema(
  tables: readonly SyncedTableInfo[]
): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER_TS);
  lines.push("");
  lines.push('import { column, Schema, Table } from "@powersync/web";');
  lines.push("");

  for (const t of tables) {
    lines.push(`const ${t.name} = new Table({`);
    for (const c of t.columns) {
      for (const commentLine of commentLinesFor(c.needsComment)) {
        lines.push(`  ${commentLine}`);
      }
      lines.push(`  ${c.name}: column.${c.psType},`);
    }
    lines.push("});");
    lines.push("");
  }

  lines.push(
    "// Server-only tables (users, user_preferences, push_subscriptions) are"
  );
  lines.push(
    "// intentionally excluded — managed server-side and never sync to the client."
  );
  lines.push("export const appSchema = new Schema({");
  for (const t of tables) {
    lines.push(`  ${t.name},`);
  }
  lines.push("});");

  return `${lines.join("\n")}\n`;
}

export function generateSyncedColumns(
  tables: readonly SyncedTableInfo[]
): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER_TS);
  lines.push("");
  lines.push(
    "// Only client-synced tables are listed here. Server-only tables (users,"
  );
  lines.push(
    "// user_preferences, push_subscriptions) are excluded — the DELETE handler"
  );
  lines.push(
    "// relies on every synced table having a deleted_at column for soft-delete."
  );
  lines.push("export const SYNCED_TABLE_NAMES = [");
  for (const t of tables) {
    lines.push(`  "${t.name}",`);
  }
  lines.push("] as const;");
  lines.push("");
  lines.push(
    "export type SyncedTableName = (typeof SYNCED_TABLE_NAMES)[number];"
  );
  lines.push("");
  lines.push(
    "export const SYNCED_TABLES: ReadonlySet<SyncedTableName> = new Set("
  );
  lines.push("  SYNCED_TABLE_NAMES");
  lines.push(");");
  lines.push("");
  lines.push("export const SYNCED_COLUMNS = {");
  for (const t of tables) {
    lines.push(`  ${t.name}: new Set([`);
    for (const colName of t.columnNames) {
      lines.push(`    "${colName}",`);
    }
    lines.push("  ]),");
  }
  lines.push("} satisfies Record<SyncedTableName, ReadonlySet<string>>;");

  return `${lines.join("\n")}\n`;
}

function writeGenerated(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf-8");
  console.log(`Generated ${path}`);
}

function main(): void {
  const projectRoot = join(import.meta.dirname, "..");
  const tables = collectSyncedTables(schema, SERVER_ONLY_TABLES);

  writeGenerated(
    join(projectRoot, "powersync", "sync-config.yaml"),
    generateSyncConfigYaml(tables)
  );
  writeGenerated(
    join(projectRoot, "src", "sync", "schema.ts"),
    generateClientSchema(tables)
  );
  writeGenerated(
    join(projectRoot, "src", "sync", "synced-columns.ts"),
    generateSyncedColumns(tables)
  );
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];

if (invokedDirectly) {
  main();
}
