import { describe, expect, it } from "vitest";
import {
  collectSyncedTables,
  generateClientSchema,
  generateSyncConfigYaml,
  generateSyncedColumns,
  mapColumnType,
  SERVER_ONLY_TABLES,
  type SyncedTableInfo,
} from "./generate-sync";

const UNKNOWN_TYPE_PATTERN = /PgJsonb/;
const UNKNOWN_TYPE_HINT_PATTERN = /scripts\/generate-sync\.ts/;
const YAML_HEADER_PATTERN = /^# Generated by scripts\/generate-sync\.ts/;
const TS_HEADER_PATTERN = /^\/\/ Generated by scripts\/generate-sync\.ts/;
const INDENTED_ID_COLUMN_PATTERN = /^\s{2}id:\s*column\./m;

const TABLES_FIXTURE: readonly SyncedTableInfo[] = [
  {
    name: "goals",
    columnNames: ["id", "user_id", "target_value", "deleted_at"],
    columns: [
      { name: "user_id", psType: "text", needsComment: null },
      { name: "target_value", psType: "integer", needsComment: null },
      { name: "deleted_at", psType: "text", needsComment: null },
    ],
  },
  {
    name: "items",
    columnNames: ["id", "user_id", "purchase_price", "deleted_at"],
    columns: [
      { name: "user_id", psType: "text", needsComment: null },
      { name: "purchase_price", psType: "text", needsComment: "numeric" },
      { name: "deleted_at", psType: "text", needsComment: null },
    ],
  },
  {
    name: "tricks",
    columnNames: ["id", "user_id", "languages", "is_silent", "deleted_at"],
    columns: [
      { name: "user_id", psType: "text", needsComment: null },
      { name: "languages", psType: "text", needsComment: "array" },
      { name: "is_silent", psType: "integer", needsComment: "boolean" },
      { name: "deleted_at", psType: "text", needsComment: null },
    ],
  },
];

describe("mapColumnType", () => {
  const textTypes = [
    "PgUUID",
    "PgText",
    "PgVarchar",
    "PgChar",
    "PgTimestamp",
    "PgTimestampString",
    "PgDate",
    "PgDateString",
    "PgTime",
  ];
  for (const t of textTypes) {
    it(`maps ${t} to text with no comment`, () => {
      expect(mapColumnType(t)).toEqual({ psType: "text", needsComment: null });
    });
  }

  it("maps PgArray to text with array comment", () => {
    expect(mapColumnType("PgArray")).toEqual({
      psType: "text",
      needsComment: "array",
    });
  });

  it("maps PgNumeric to text with numeric comment", () => {
    expect(mapColumnType("PgNumeric")).toEqual({
      psType: "text",
      needsComment: "numeric",
    });
  });

  const integerTypes = [
    "PgInteger",
    "PgSmallInt",
    "PgSerial",
    "PgSmallSerial",
    "PgBigSerial53",
    "PgBigSerial64",
  ];
  for (const t of integerTypes) {
    it(`maps ${t} to integer with no comment`, () => {
      expect(mapColumnType(t)).toEqual({
        psType: "integer",
        needsComment: null,
      });
    });
  }

  it("maps PgBoolean to integer with boolean comment", () => {
    expect(mapColumnType("PgBoolean")).toEqual({
      psType: "integer",
      needsComment: "boolean",
    });
  });

  it("throws on unknown columnType with helpful message", () => {
    expect(() => mapColumnType("PgJsonb")).toThrow(UNKNOWN_TYPE_PATTERN);
    expect(() => mapColumnType("PgJsonb")).toThrow(UNKNOWN_TYPE_HINT_PATTERN);
  });
});

describe("collectSyncedTables", () => {
  it("excludes denylisted tables and returns remaining tables alphabetically", async () => {
    const schema = await import("../src/db/schema");

    const tables = collectSyncedTables(schema, SERVER_ONLY_TABLES);

    const names = tables.map((t) => t.name);
    expect(names).toEqual([
      "goals",
      "item_tags",
      "item_tricks",
      "items",
      "performances",
      "practice_session_tricks",
      "practice_sessions",
      "setlist_tricks",
      "setlists",
      "tags",
      "trick_tags",
      "tricks",
    ]);
  });

  it("places id first in columnNames and excludes id from columns", async () => {
    const schema = await import("../src/db/schema");

    const tables = collectSyncedTables(schema, SERVER_ONLY_TABLES);

    for (const t of tables) {
      expect(t.columnNames[0]).toBe("id");
      expect(t.columns.some((c) => c.name === "id")).toBe(false);
    }
  });

  it("marks array, boolean, and numeric columns with comments", async () => {
    const schema = await import("../src/db/schema");

    const tables = collectSyncedTables(schema, SERVER_ONLY_TABLES);
    const tricks = tables.find((t) => t.name === "tricks");
    const items = tables.find((t) => t.name === "items");
    const setlists = tables.find((t) => t.name === "setlists");

    expect(
      tricks?.columns.find((c) => c.name === "is_camera_friendly")?.needsComment
    ).toBe("boolean");
    expect(
      tricks?.columns.find((c) => c.name === "languages")?.needsComment
    ).toBe("array");
    expect(
      items?.columns.find((c) => c.name === "purchase_price")?.needsComment
    ).toBe("numeric");
    expect(setlists?.columns.find((c) => c.name === "tags")?.needsComment).toBe(
      "array"
    );
    expect(
      setlists?.columns.find((c) => c.name === "requirements")?.needsComment
    ).toBe("array");
  });

  it("skips non-table exports", () => {
    const schema = {
      tricks: { fake: true },
      notATable: "hello",
      alsoNot: 42,
    };
    expect(collectSyncedTables(schema, new Set())).toEqual([]);
  });
});

describe("generateSyncConfigYaml", () => {
  it("includes edition 3 config and auto_subscribe stream", () => {
    const yaml = generateSyncConfigYaml(TABLES_FIXTURE);
    expect(yaml).toMatch(YAML_HEADER_PATTERN);
    expect(yaml).toContain("config:\n  edition: 3");
    expect(yaml).toContain("streams:\n  user_data:\n    auto_subscribe: true");
    expect(yaml.endsWith("\n")).toBe(true);
  });

  it("emits one auth.user_id() query per table in input order", () => {
    const yaml = generateSyncConfigYaml(TABLES_FIXTURE);
    expect(yaml).toContain(
      "- SELECT * FROM goals WHERE user_id = auth.user_id()"
    );
    expect(yaml).toContain(
      "- SELECT * FROM items WHERE user_id = auth.user_id()"
    );
    expect(yaml).toContain(
      "- SELECT * FROM tricks WHERE user_id = auth.user_id()"
    );
    const goalsIdx = yaml.indexOf("FROM goals");
    const itemsIdx = yaml.indexOf("FROM items");
    const tricksIdx = yaml.indexOf("FROM tricks");
    expect(goalsIdx).toBeLessThan(itemsIdx);
    expect(itemsIdx).toBeLessThan(tricksIdx);
  });

  it("is deterministic — identical input produces identical output", () => {
    expect(generateSyncConfigYaml(TABLES_FIXTURE)).toBe(
      generateSyncConfigYaml(TABLES_FIXTURE)
    );
  });
});

describe("generateClientSchema", () => {
  it("imports from @powersync/web and starts with header", () => {
    const ts = generateClientSchema(TABLES_FIXTURE);
    expect(ts).toMatch(TS_HEADER_PATTERN);
    expect(ts).toContain(
      'import { column, Schema, Table } from "@powersync/web";'
    );
  });

  it("emits boolean, array, and numeric comments next to the right columns", () => {
    const ts = generateClientSchema(TABLES_FIXTURE);
    expect(ts).toContain(
      "// PostgreSQL booleans are stored as integers (0/1) in SQLite."
    );
    expect(ts).toContain(
      "// PostgreSQL text[] arrays are serialized as JSON strings by PowerSync."
    );
    expect(ts).toContain(
      "// Stored as text to preserve exact decimal precision"
    );
    const arrayCommentIdx = ts.indexOf(
      "// PostgreSQL text[] arrays are serialized"
    );
    const languagesIdx = ts.indexOf("languages: column.text");
    expect(arrayCommentIdx).toBeLessThan(languagesIdx);
    expect(languagesIdx - arrayCommentIdx).toBeLessThan(200);
  });

  it("excludes id from every new Table but lists tables in appSchema", () => {
    const ts = generateClientSchema(TABLES_FIXTURE);
    expect(ts).not.toMatch(INDENTED_ID_COLUMN_PATTERN);
    expect(ts).toContain("export const appSchema = new Schema({");
    expect(ts).toContain("  goals,");
    expect(ts).toContain("  items,");
    expect(ts).toContain("  tricks,");
  });

  it("is deterministic", () => {
    expect(generateClientSchema(TABLES_FIXTURE)).toBe(
      generateClientSchema(TABLES_FIXTURE)
    );
  });
});

describe("generateSyncedColumns", () => {
  it("emits SYNCED_TABLE_NAMES as const tuple", () => {
    const ts = generateSyncedColumns(TABLES_FIXTURE);
    expect(ts).toContain("export const SYNCED_TABLE_NAMES = [");
    expect(ts).toContain('"goals",');
    expect(ts).toContain("] as const;");
    expect(ts).toContain(
      "export type SyncedTableName = (typeof SYNCED_TABLE_NAMES)[number];"
    );
  });

  it("emits SYNCED_COLUMNS satisfies Record<SyncedTableName, ReadonlySet<string>>", () => {
    const ts = generateSyncedColumns(TABLES_FIXTURE);
    expect(ts).toContain(
      "} satisfies Record<SyncedTableName, ReadonlySet<string>>;"
    );
  });

  it("places id first in every column set", () => {
    const ts = generateSyncedColumns(TABLES_FIXTURE);
    const goalsBlock = ts.slice(
      ts.indexOf("goals: new Set(["),
      ts.indexOf("]),", ts.indexOf("goals: new Set(["))
    );
    const firstEntry = goalsBlock.split("\n")[1] ?? "";
    expect(firstEntry.trim()).toBe('"id",');
  });

  it("is deterministic", () => {
    expect(generateSyncedColumns(TABLES_FIXTURE)).toBe(
      generateSyncedColumns(TABLES_FIXTURE)
    );
  });
});
